# ref: https://docs.codecov.com/docs/codecovyml-reference
coverage:
  range: 85..100
  round: down
  precision: 1
  status:
    project:
      default:
        threshold: 1%

comment:
  layout: "files"
  require_changes: yes

    #ignore:
    #  - "**/tests"
